---
- name: test subutai module
  
  hosts: localhost
  port: 2222
  remote_user: subutai


  tasks:
    - name: run subutai import nginx
      subutai_import:
        container: 'nginx'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: run subutai destroy nginx
      subutai_destroy:
        container: 'nginx'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: run subutai stop management
      subutai_stop:
        container: 'management'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'


    - name: run subutai start management
      subutai_start:
        container: 'management'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: backup management
      subutai_backup:
        container: 'management'
        full_backup: true 
        stop_container: true
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'


    - name: clone management
      subutai_clone:
        parent: 'management'
        child: 'management-test'

      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: cleanup enviroment
      subutai_cleanup:

      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: update container
      subutai_update:
        container: management
      become: true
      register: testout


    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: checkpoint container
      subutai_checkpoint:
        container: 'management'
        stop_container: true
    
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: restore checkpoint container
      subutai_checkpoint:
        container: 'management'
        restore: True

      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: config container
      subutai_config:
        container: 'management'
        operation: add 
        key: foo 
        value: bar 
    
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: delete config container
      subutai_config:
        container: 'management'
        operation: 'del'
        key: 'foo'
        value: 'bar'

      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'



