---
- name: test subutai module
  
  hosts: localhost
  port: 2222
  remote_user: subutai


  tasks:
    - name: run subutai import nginx
      subutai_import:
        container: 'nginx'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: run subutai destroy nginx
      subutai_destroy:
        container: 'nginx'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'