---
- name: test subutai module
  
  hosts: localhost
  port: 2222
  remote_user: subutai


  tasks:
    - name: run subutai import nginx
      subutai_import:
        container: 'nginx'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: run subutai destroy nginx
      subutai_destroy:
        container: 'nginx'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: run subutai stop management
      subutai_stop:
        container: 'management'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'


    - name: run subutai start management
      subutai_start:
        container: 'management'
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'

    - name: backup management
      subutai_backup:
        container: 'management'
        full_backup: true 
        stop_container: true
      become: true
      register: testout

    - name: dump test output
      debug:
        msg: '{{ testout }}'


